name: i9500_Android8_Build
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Cek
        uses: actions/checkout@v4

      - name: Sunucuda Yer AÃ§
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          
      - name: Ccache Yukle
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ccache-i9500-${{ github.run_id }}
          restore-keys: ccache-i9500-

      - name: Build Hazirliklari
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential zip curl libstdc++6 git python3 python2
          git config --global user.email "pepee@polonya.com"
          git config --global user.name "Pepee"
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          export PATH=~/bin:$PATH
          repo init -u https://github.com/LineageOS/android.git -b lineage-15.1 --depth=1
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

      - name: Cihaz Dosyalari
        run: |
          git clone https://github.com/LineageOS/android_device_samsung_ja3g -b lineage-15.1 device/samsung/ja3g
          git clone https://github.com/LineageOS/android_kernel_samsung_exynos5410 -b lineage-15.1 kernel/samsung/exynos5410

      - name: Derleme Baslat
        run: |
          export USE_CCACHE=1
          export CCACHE_EXEC=/usr/bin/ccache
          ccache -M 10G
          source build/envsetup.sh
          lunch lineage_ja3g-userdebug || true
          make mka bacon -j$(nproc --all) || echo "Hata olsa da devam et"

      - name: Dosyayi Yukle
        uses: actions/upload-artifact@v4
        with:
          name: I9500-Android-8-ROM
          path: out/target/product/ja3g/*.zip
