name: i9500_Android8_Build
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04  # <--- İşte burayı "focal" (20.04) yaptık, Python 2 burada var!
    steps:
      - name: Kodu Cek
        uses: actions/checkout@v4

      - name: Sunucuyu Hazirla (Antika Paketler)
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-8-jdk python2 python2-dev python3 git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z.1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip bc ccache

      - name: Repo Aracini Kur
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          sudo ln -sf ~/bin/repo /usr/bin/repo

      - name: Kodlari Esitle (Repo Sync)
        run: |
          git config --global user.email "pepee@polonya.com"
          git config --global user.name "Pepee"
          repo init -u https://github.com/LineageOS/android.git -b lineage-15.1 --depth=1
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

      - name: Cihaz Dosyalari
        run: |
          git clone https://github.com/LineageOS/android_device_samsung_ja3g -b lineage-15.1 device/samsung/ja3g
          git clone https://github.com/LineageOS/android_kernel_samsung_exynos5410 -b lineage-15.1 kernel/samsung/exynos5410

      - name: Derlemeyi Patlat
        run: |
          export USE_CCACHE=1
          ccache -M 10G
          source build/envsetup.sh
          # Python 2'yi varsayılan yapalım ki hata vermesin
          sudo ln -sf /usr/bin/python2 /usr/bin/python
          lunch lineage_ja3g-userdebug || true
          make mka bacon -j$(nproc --all)

      - name: ROM Dosyasini Al
        uses: actions/upload-artifact@v4
        with:
          name: I9500-Android8-ROM
          path: out/target/product/ja3g/*.zip

